### ISSUE TITLE
Page number not updating when chaning page_parameter

### ISSUE THREAD

**Issue by poltorres0999** [lixxu/flask-paginate#76]
Hi,
I'm experimenting an issue when chaning the default page_parameter to have two pagination objects, since the page number is not chaging when selecting any of the pages of any of the two tables, the data is changing correctly and the query string is also updating it's values correctly.

Thank you, 

Pol

**Comment by lixxu** [comment]
Sorry, I'm not quite sure what do you mean. Could you paste some codes for example?

**Comment by machines94** [comment]
at the moment I used two paginations on same page but after I added customizable page_parameter, page update number, doesn't work;
![image](https://user-images.githubusercontent.com/15922079/71897815-51f73b80-3160-11ea-8dc8-330f57819e07.png)

**Comment by lixxu** [comment]
`two paginations`? you mean `two Pagination instances`?

**Comment by kelj0** [comment]
Hello @poltorres0999 I also had the same issue. I found this bug in the code and I fixed it. I also found one other bug which I also fixed.
Here is PR https://github.com/lixxu/flask-paginate/pull/85
@lixxu here's description
Lets say we have an app.py
![image](https://user-images.githubusercontent.com/35850075/94112699-20d1af00-fe46-11ea-86ed-39755aad17a4.png)

So we want to specify a custom page and per page parameters ('p' and 'pp').
Frontend is 
![image](https://user-images.githubusercontent.com/35850075/94112842-4b236c80-fe46-11ea-883f-3c1e172ad9d8.png)

Expected behaviour is that we get page looking like this
![image](https://user-images.githubusercontent.com/35850075/94113068-9ccbf700-fe46-11ea-9ada-f029939089cc.png)

which we get!

But the problem is when you click '2' or '3' or any other number in the pagination.info generated area this happens.
![image](https://user-images.githubusercontent.com/35850075/94113154-c127d380-fe46-11ea-95a3-63f8996280f4.png)
As you can see page refreshed, showed new results but pagination.info didn't change.
So I fixed that and I also found a new bug.
In the same example when you want to have different 'per_page' items (in this case 'pp') it works partly and it breaks pagination
![image](https://user-images.githubusercontent.com/35850075/94113378-1532b800-fe47-11ea-86c3-5ba91188b825.png)

Can you spot the problem? The number of pagination pages in the pagination.info didn't change. That means if we go to the last page, we will get no results 
![image](https://user-images.githubusercontent.com/35850075/94113470-35fb0d80-fe47-11ea-99f1-5e73172ed6b9.png)
I fixed that issue also in the PR

**Comment by lixxu** [comment]
version `0.7.1` fixed the issue. Your PR can not fix it if `page_parameter` and `per_page_parameter` set.

**Comment by aleksandar** [comment]
The issue is still relevant in version 0.7.1. Have two tables and two Pagination objects, when change the page_parameter param for one. Pagination links don't show right page for a Pagination object which doesn't have default page param.

**Comment by kelj0** [comment]
hey @aleksandar  try to use my fix here https://github.com/lixxu/flask-paginate/pull/85/commits 😃 
Lixxus fix doesn't work for me also.
